In [5]:
import pandas as pd
df = pd.read_csv("retail_sales_dashboard_dataset.csv")

In [7]:
print (df.shape)

(3000, 13)

In [9]:
df.head

<bound method NDFrame.head of       order_id  order_date         product     category  quantity   price  \
0     ORD10000  13/07/2024    Office Chair    Furniture         3   39.79
1     ORD10001  27/04/2024        Backpack  Accessories         5  229.87
2     ORD10002  04/08/2024  Wireless Mouse  Electronics         5    7.72
3     ORD10003  12/01/2024       Bookshelf    Furniture         2  204.67
4     ORD10004  09/12/2024    Laptop Stand  Electronics         5  281.25
...        ...         ...             ...          ...       ...     ...
2995  ORD12995  20/10/2024        Backpack  Accessories         4  144.57
2996  ORD12996  05/12/2024  Desk Organizer   Stationery         3  293.80
2997  ORD12997  02/08/2024        Pen Pack   Stationery         3  195.59
2998  ORD12998  03/06/2024        Pen Pack   Stationery         2   23.38
2999  ORD12999  29/03/2024        Backpack  Accessories         3   70.72

      total_sales           city    store sales_channel payment_method  \
0           96.69          Abuja  Store A       Offline           Card
1         1149.35           Kano  Store A       Offline           Card
2           30.11          Lagos  Store B       Offline   Mobile Money
3          331.57         Ibadan  Store A        Online       Transfer
4         1251.56          Abuja  Store C       Offline   Mobile Money
...           ...            ...      ...           ...            ...
2995       543.58  Port Harcourt  Store B        Online       Transfer
2996       696.31         Ibadan  Store A       Offline       Transfer
2997       563.30         Ibadan  Store C       Offline   Mobile Money
2998        42.55  Port Harcourt  Store B        Online           Cash
2999       197.31          Lagos  Store C       Offline           Card

      discount  profit
0         0.19   21.08
1         0.00  242.91
2         0.22    8.18
3         0.19  112.09
4         0.11  384.87
...        ...     ...
2995      0.06  164.82
2996      0.21   96.77
2997      0.04  130.95
2998      0.09    8.02
2999      0.07   53.53

[3000 rows x 13 columns]>

In [11]:
df.info

<bound method DataFrame.info of       order_id  order_date         product     category  quantity   price  \
0     ORD10000  13/07/2024    Office Chair    Furniture         3   39.79
1     ORD10001  27/04/2024        Backpack  Accessories         5  229.87
2     ORD10002  04/08/2024  Wireless Mouse  Electronics         5    7.72
3     ORD10003  12/01/2024       Bookshelf    Furniture         2  204.67
4     ORD10004  09/12/2024    Laptop Stand  Electronics         5  281.25
...        ...         ...             ...          ...       ...     ...
2995  ORD12995  20/10/2024        Backpack  Accessories         4  144.57
2996  ORD12996  05/12/2024  Desk Organizer   Stationery         3  293.80
2997  ORD12997  02/08/2024        Pen Pack   Stationery         3  195.59
2998  ORD12998  03/06/2024        Pen Pack   Stationery         2   23.38
2999  ORD12999  29/03/2024        Backpack  Accessories         3   70.72

      total_sales           city    store sales_channel payment_method  \
0           96.69          Abuja  Store A       Offline           Card
1         1149.35           Kano  Store A       Offline           Card
2           30.11          Lagos  Store B       Offline   Mobile Money
3          331.57         Ibadan  Store A        Online       Transfer
4         1251.56          Abuja  Store C       Offline   Mobile Money
...           ...            ...      ...           ...            ...
2995       543.58  Port Harcourt  Store B        Online       Transfer
2996       696.31         Ibadan  Store A       Offline       Transfer
2997       563.30         Ibadan  Store C       Offline   Mobile Money
2998        42.55  Port Harcourt  Store B        Online           Cash
2999       197.31          Lagos  Store C       Offline           Card

      discount  profit
0         0.19   21.08
1         0.00  242.91
2         0.22    8.18
3         0.19  112.09
4         0.11  384.87
...        ...     ...
2995      0.06  164.82
2996      0.21   96.77
2997      0.04  130.95
2998      0.09    8.02
2999      0.07   53.53

[3000 rows x 13 columns]>

In [13]:
df.describe

<bound method NDFrame.describe of       order_id  order_date         product     category  quantity   price  \
0     ORD10000  13/07/2024    Office Chair    Furniture         3   39.79
1     ORD10001  27/04/2024        Backpack  Accessories         5  229.87
2     ORD10002  04/08/2024  Wireless Mouse  Electronics         5    7.72
3     ORD10003  12/01/2024       Bookshelf    Furniture         2  204.67
4     ORD10004  09/12/2024    Laptop Stand  Electronics         5  281.25
...        ...         ...             ...          ...       ...     ...
2995  ORD12995  20/10/2024        Backpack  Accessories         4  144.57
2996  ORD12996  05/12/2024  Desk Organizer   Stationery         3  293.80
2997  ORD12997  02/08/2024        Pen Pack   Stationery         3  195.59
2998  ORD12998  03/06/2024        Pen Pack   Stationery         2   23.38
2999  ORD12999  29/03/2024        Backpack  Accessories         3   70.72

      total_sales           city    store sales_channel payment_method  \
0           96.69          Abuja  Store A       Offline           Card
1         1149.35           Kano  Store A       Offline           Card
2           30.11          Lagos  Store B       Offline   Mobile Money
3          331.57         Ibadan  Store A        Online       Transfer
4         1251.56          Abuja  Store C       Offline   Mobile Money
...           ...            ...      ...           ...            ...
2995       543.58  Port Harcourt  Store B        Online       Transfer
2996       696.31         Ibadan  Store A       Offline       Transfer
2997       563.30         Ibadan  Store C       Offline   Mobile Money
2998        42.55  Port Harcourt  Store B        Online           Cash
2999       197.31          Lagos  Store C       Offline           Card

      discount  profit
0         0.19   21.08
1         0.00  242.91
2         0.22    8.18
3         0.19  112.09
4         0.11  384.87
...        ...     ...
2995      0.06  164.82
2996      0.21   96.77
2997      0.04  130.95
2998      0.09    8.02
2999      0.07   53.53

[3000 rows x 13 columns]>

In [15]:
df

,order_id,order_date,product,category,quantity,price,total_sales,city,store,sales_channel,payment_method,discount,profit
0,ORD10000,13/07/2024,Office Chair,Furniture,3,39.79,96.69,Abuja,Store A,Offline,Card,0.19,21.08
1,ORD10001,27/04/2024,Backpack,Accessories,5,229.87,1149.35,Kano,Store A,Offline,Card,0.00,242.91
2,ORD10002,04/08/2024,Wireless Mouse,Electronics,5,7.72,30.11,Lagos,Store B,Offline,Mobile Money,0.22,8.18
3,ORD10003,12/01/2024,Bookshelf,Furniture,2,204.67,331.57,Ibadan,Store A,Online,Transfer,0.19,112.09
4,ORD10004,09/12/2024,Laptop Stand,Electronics,5,281.25,1251.56,Abuja,Store C,Offline,Mobile Money,0.11,384.87
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,ORD12995,20/10/2024,Backpack,Accessories,4,144.57,543.58,Port Harcourt,Store B,Online,Transfer,0.06,164.82
2996,ORD12996,05/12/2024,Desk Organizer,Stationery,3,293.80,696.31,Ibadan,Store A,Offline,Transfer,0.21,96.77
2997,ORD12997,02/08/2024,Pen Pack,Stationery,3,195.59,563.30,Ibadan,Store C,Offline,Mobile Money,0.04,130.95
2998,ORD12998,03/06/2024,Pen Pack,Stationery,2,23.38,42.55,Port Harcourt,Store B,Online,Cash,0.09,8.02
2999,ORD12999,29/03/2024,Backpack,Accessories,3,70.72,197.31,Lagos,Store C,Offline,Card,0.07,53.53

In [17]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2995    False
2996    False
2997    False
2998    False
2999    False
Length: 3000, dtype: bool

In [23]:
df.isnull().sum()

order_id          0
order_date        0
product           0
category          0
quantity          0
price             0
total_sales       0
city              0
store             0
sales_channel     0
payment_method    0
discount          0
profit            0
dtype: int64

In [27]:
df.dropna()

,order_id,order_date,product,category,quantity,price,total_sales,city,store,sales_channel,payment_method,discount,profit
0,ORD10000,13/07/2024,Office Chair,Furniture,3,39.79,96.69,Abuja,Store A,Offline,Card,0.19,21.08
1,ORD10001,27/04/2024,Backpack,Accessories,5,229.87,1149.35,Kano,Store A,Offline,Card,0.00,242.91
2,ORD10002,04/08/2024,Wireless Mouse,Electronics,5,7.72,30.11,Lagos,Store B,Offline,Mobile Money,0.22,8.18
3,ORD10003,12/01/2024,Bookshelf,Furniture,2,204.67,331.57,Ibadan,Store A,Online,Transfer,0.19,112.09
4,ORD10004,09/12/2024,Laptop Stand,Electronics,5,281.25,1251.56,Abuja,Store C,Offline,Mobile Money,0.11,384.87
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,ORD12995,20/10/2024,Backpack,Accessories,4,144.57,543.58,Port Harcourt,Store B,Online,Transfer,0.06,164.82
2996,ORD12996,05/12/2024,Desk Organizer,Stationery,3,293.80,696.31,Ibadan,Store A,Offline,Transfer,0.21,96.77
2997,ORD12997,02/08/2024,Pen Pack,Stationery,3,195.59,563.30,Ibadan,Store C,Offline,Mobile Money,0.04,130.95
2998,ORD12998,03/06/2024,Pen Pack,Stationery,2,23.38,42.55,Port Harcourt,Store B,Online,Cash,0.09,8.02
2999,ORD12999,29/03/2024,Backpack,Accessories,3,70.72,197.31,Lagos,Store C,Offline,Card,0.07,53.53

In [31]:
df['order_date'] = pd.to_datetime(df['order_date'], dayfirst=True)

In [33]:
df['order_date'].head()
df.dtypes

order_id                  object
order_date        datetime64[ns]
product                   object
category                  object
quantity                   int64
price                    float64
total_sales              float64
city                      object
store                     object
sales_channel             object
payment_method            object
discount                 float64
profit                   float64
dtype: object

In [53]:
df.to_csv("outputs/cleaned_retail_data.csv", index=False)